spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes_dev
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
