spring:
  servlet:
    multipart:
      max-file-size: 4MB
  application:
    name: recipe-manager
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5-nano
          temperature: 1
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
    domain: ${JWT_DOMAIN}
mail-trap:
  mail-from: mailtrap@sebastianklimas@op.pl